### PR TITLE
basic codacy config

### PR DESCRIPTION
**Pull request by mirceanis**
This adds a basic configuration for codacy using a config file.
This should allow us some extra liberties in tests.

### CODE REVIEW

**Comment by ugoamanoh** [comment]
Can we exclude .md files?

**Comment by mirceanis** [comment]
@ugoamanoh 

we can, but I deliberately omitted the engine that checks markdown.
I assume that it will simply ignore md files on its own.
If not, we can deliberately ignore `**.md` or specify the engine as disabled instead of omitting it.

**Comment by ugoamanoh** [comment]
It actually flags some issues on the README.md
https://app.codacy.com/app/uport-project/uport-android-sdk/pullRequest?prid=2888167

**Comment by mirceanis** [comment]
> It actually flags some issues on the README.md
> https://app.codacy.com/app/uport-project/uport-android-sdk/pullRequest?prid=2888167

@ugoamanoh Yes, but that is another PR that hasn't seen this new config.
We'll need to merge develop into the other PR branches after this is integrated

**Comment by ugoamanoh** [comment]
Ok just wanted to know if this was covered in your config changes

**Pull request merged**
