### PR TITLE
Callbacks refactoring

### LINKED ISSUE #13: [support] refactor callbacks into coroutines
Async is handled differently in different modules. Some use callbacks, some coroutines, some both.
Since coroutines are here to stay, all async functionality should be ported to that pattern so the code becomes much more readable.

### PR DESCRIPTION
**Pull request by RiccardoM**
Fix #13

### CODE REVIEW

**Comment by RiccardoM** [comment]
If I will have any question I'll ask them inside the proper issue. 

About this one, the only thing I did was to remove the callbacks and let eventual exceptions flow back to the top of the stack like normal code execution. This reduces a lot the number of try/catch necessary and simplifies the flow of execution by quite a bit. 
The tests were missing and I didn't add them because I haven't really taken a deep look at the code and so IDK the weak points that should be tested and the edge cases there might be. 
I hope everything is as expected.

**Comment by RiccardoM** [comment]
@mirceanis I thought I ran all the tests at the time and was passing all of them 🤔 What about setting up Travis or something else and actually doing checks on PRs? That could be great to see if I actually pass the tests or not.
Anyway, I will probably close this PR and open up another with the proper conversions made again, but I think that will be useless unless two conditions are met: 
1. There is actually a CI system that checks for errors or incompatibility. 
2. The PR is merged before any development continues. 

Note that changing all callbacks to suspend functions will make future development a lot easier and quick, so I don't see why this isn't prioritized as the more time you have callbacks inside the code and the less the code stays easy to comprehend.

**Comment by mirceanis** [comment]
You are right, of course.

In the meantime I've set up circleCI to run the jvm tests.
There are also some instrumented tests that need to pass and those have to be run manually for the moment.

The issue was originally just a reminder for me to circle back to coroutines. I didn't expect a contribution so early :)
There are a few places where callbacks should still be exposed. For example, the `signer` module which is being used in other projects and it relies on Android callbacks, where some are activity results.

**Comment by mirceanis** [comment]
I have to close this PR because it's too outdated.
I failed to review it in a timely fashion and that led to too many conflicts.
I'd like to incorporate your contributions but it's simply too messy at this point because a lot has changed in the origin. A fresh approach is needed.

**Pull request closed without merging**
